/* eslint-disable security/detect-non-literal-fs-filename */
import { readFile, access, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { configure as configureHusky } from '@gautaz/husky';
import { dump } from 'js-yaml';
import { findUp } from 'find-up';

export const readJSONFile = async (path) => {
  try {
    // The purpose of this library is to scaffold based on existing project content
    const json = await readFile(path, 'utf8');
    return JSON.parse(json);
  } catch (error) {
    throw new Error(`failed to extract JSON from ${path} (${error.message})`, { cause: error });
  }
};

export const extractPackageDetails = async ({ url, extract = (x) => x, logger }) => {
  try {
    const packageJSONPath = await findUp('package.json', { cwd: path.dirname(new URL(url).pathname) });
    return extract(await readJSONFile(packageJSONPath));
  } catch (error) {
    logger.error(`Unable to get ${url} package details:`, error.message);
    throw error;
  }
};

const jsRulesStrings = (logger) =>
  extractPackageDetails({
    url: import.meta.url,
    extract: ({ name, version }) => ({
      defaultLogPreamble: `${name}[${version}]:`,
      defaultEditWarning: `DO NOT EDIT THIS FILE AS IT IS GENERATED BY ${name}`,
    }),
    logger,
  });

export const toYAML = (x) => dump(x);
export const toMultiline = (array) => `${array.join('\n')}\n`;
export const addHeader =
  (prefix = '', postfix = '\n') =>
  (header = '') => {
    const iterableHeader =
      Object.hasOwn(new Object(header), Symbol.iterator) && Object.prototype.toString.call(header) !== '[object String]'
        ? header
        : [header];
    let formattedHeader = '';
    for (const header_ of iterableHeader) {
      formattedHeader += `${`${prefix}${header_}`.trimEnd()}${postfix}`;
    }
    return (content = '') => `${formattedHeader}${content}`;
  };
export const addHashedHeader = addHeader('# ');
export const addSlashHeader = addHeader('// ');

const prettierConfiguration = {
  singleQuote: true,
  semi: true,
  tabWidth: 2,
  printWidth: 120,
};
const prettierIgnore = ['__fixtures__', 'helm', '*.json', '*.yml', '*.yaml'];

const configurationFiles = async (addWarningHeader, addJsWarningHeader) => {
  const eslintTemplate = await readFile(`${path.dirname(new URL(import.meta.url).pathname)}/template.eslint.config.js`);
  return {
    'eslint.config.js': {
      configuration: eslintTemplate.toString(),
      formatters: [addJsWarningHeader],
    },
    '.prettierrc.yaml': {
      configuration: prettierConfiguration,
      formatters: [toYAML, addWarningHeader],
    },
    '.prettierignore': {
      configuration: prettierIgnore,
      formatters: [toMultiline, addWarningHeader],
    },
  };
};

const setConfiguration = (logStep) => (files) =>
  Promise.all(
    Object.entries(files).map(async ([configurationPath, { configuration, formatters }]) => {
      let content = configuration;
      for (const format of formatters) {
        content = format(content);
      }
      // The modified file location depends on the structure of the project being scaffolded
      await writeFile(configurationPath, content);
      logStep(`${configurationPath} deployed`);
    }),
  );

const lintCommand = 'npx --no-install eslint .';
const addAdocTag = (commands) => ['# tag::commands[]', ...commands, '# end::commands[]'];

const huskyHooks = {
  'pre-commit': addAdocTag([lintCommand]),
  'pre-push': addAdocTag([`npx --no-install r2d2bzh-js-rules isWIP || ${lintCommand} && npm test`]),
};

const setHuskyHooks = (logger) => {
  const husky = configureHusky({
    log: logger.log.bind(logger),
    error: logger.error.bind(logger),
  });
  return (hooks) => {
    husky.install();
    for (const [name, commands] of Object.entries(hooks)) {
      const hook = path.join('.husky', name);
      husky.set(hook, '');
      for (const command of commands) {
        husky.add(hook, command);
      }
      logger.log(`${hook} deployed`);
    }
  };
};

const fileExists = async (path) => {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
};

const showEslintWarning = async (logger) => {
  if ((await fileExists('.eslintrc.yaml')) || (await fileExists('.eslintignore')))
    logger.warn(
      '\u{1B}[33m!! Please remove .eslintrc.yaml and .eslintignore files which are now ignored by Eslint v9 !!\u{1B}[0m',
    );
};

const _install = async ({ editWarning, tweakConfigurationFiles = (f) => f, tweakHuskyHooks = (h) => h, logger }) => {
  try {
    const logStep = (...arguments_) => logger.log(...arguments_);
    const configFiles = await configurationFiles(addHashedHeader(editWarning), addSlashHeader(editWarning));
    await setConfiguration(logStep)(await tweakConfigurationFiles(configFiles));
    setHuskyHooks(logger)(await tweakHuskyHooks(huskyHooks));
    await showEslintWarning(logger);
    logger.log('successfully deployed');
  } catch (error) {
    logger.error(`installation failed: ${error.message ?? error}`);
    throw error;
  }
};

export const install = async ({ logger, ...options } = {}) => {
  const defaultLogger = console;
  const { defaultLogPreamble, defaultEditWarning } = await jsRulesStrings(logger || defaultLogger);
  const defaultLoggerWithPreamble = {
    log: (...arguments_) => defaultLogger.log(defaultLogPreamble, ...arguments_),
    warn: (...arguments_) => defaultLogger.warn(defaultLogPreamble, ...arguments_),
    error: (...arguments_) => defaultLogger.error(defaultLogPreamble, ...arguments_),
  };
  return _install({
    logger: logger || defaultLoggerWithPreamble,
    editWarning: defaultEditWarning,
    ...options,
  });
};

export default {
  install,
  readJSONFile,
  extractPackageDetails,
  toMultiline,
  toYAML,
  addHeader,
  addHashedHeader,
};
